### PR TITLE
Add basic automatic online/offline message in header

### PR DESCRIPTION
**Pull request by MangoSwirl**
Functionally, this seems to be working. The only design change that's bothering me is that the online/offline message isn't vertically centered within the navbar. Can you figure out a way to do that @SCool62?

### CODE REVIEW

**Comment by MangoSwirl** [comment]
Oh, also, it doesn't look the best on mobile.

**Comment by SCool62** [comment]
I can't see the online/offline message on the page (the webpage) or in `index.html`.

**Comment by MangoSwirl** [comment]
That's because the PR hasn't merged yet. You'd have to clone the branch and preview it with live server lol.

**Comment by MangoSwirl** [comment]
It's not merged because it's not production ready. I wanted to get your view before I merged it. Also, currently the only way to make status update posts is to manually edit the database, which isn't the best. Any idea for a secure form that pushes to a Firebase database only available to admins?

**Pull request merged**
